//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Broker
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telefonosxcliente
    {
        public int idCliente { get; set; }
        public int Telefono { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
